name: boarding_group
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons:
  flutter_riverpod:
  riverpod_annotation:  
  device_info_plus:
  dio:
  intl:
  image_picker:
  firebase_core:
  logger:
  cached_network_image:
  connectivity_plus:
  dio_smart_retry: 
  path_provider:
  flutter_spinkit:
  get_storage:
  month_picker_dialog: 0.4.0
  dropdown_button2:
  flutter_localizations:

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  build_runner:
  riverpod_generator: 

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

